use cxx_qt_build::{CxxQtBuilder, QmlModule};

fn main() {
    CxxQtBuilder::new_qml_module(
        QmlModule::new("io.github.fullstacktaiye.harkness").qml_files([
            "qml/Main.qml",
            "qml/FloatingSurface.qml",
            "qml/FieldSurface.qml",
            "qml/AppTitleBar.qml",
            "qml/WindowResizeBorders.qml",
            "qml/LauncherPage.qml",
            "qml/LauncherActionCard.qml",
            "qml/SidebarProjectRow.qml",
            "qml/ProjectShellPage.qml",
            "qml/ActivityBar.qml",
            "qml/ActivityBarItem.qml",
            "qml/SidePanel.qml",
            "qml/PanelHeader.qml",
            "qml/GitActivity.qml",
            "qml/CommitSelection.qml",
            "qml/ToolbarSegment.qml",
            "qml/RepositoryToolbar.qml",
            "qml/GitPanel.qml",
            "qml/IssuesPanel.qml",
            "qml/ChecksPanel.qml",
            "qml/ChangesPanel.qml",
            "qml/DiscardPrompt.qml",
            "qml/HistoryPanel.qml",
            "qml/ReviewSurface.qml",
            "qml/RunState.qml",
            "qml/RunListPane.qml",
            "qml/RunsPanel.qml",
            "qml/RunDetailPage.qml",
        ]),
    )
    .qt_module("Network")
    .include_dir("cxx")
    .files([
        "src/approval_model.rs",
        "src/backend.rs",
        "src/changes_model.rs",
        "src/file_tree_model.rs",
        "src/hotreload.rs",
        "src/run_list_model.rs",
        "src/run_timeline_model.rs",
        "src/runs_backend.rs",
    ])
    .build();
}
