import QtQuick
import org.kde.kirigami as Kirigami

/// The words, colours and units the run surfaces share.
///
/// Instantiated rather than imported as a singleton because the QML module is
/// generated by `build.rs` from a flat file list, which has no way to mark one
/// of them `singleton`. Every run surface declares one of these and reads it as
/// `runState.*`; it draws nothing and is never laid out.
///
/// It is an `Item` and not a `QtObject` for one reason: `Kirigami.Theme` is an
/// attached property of `Item`, and the palette below is read through it. A
/// control carries the widget style's own colour set with theme inheritance
/// off — the reason `FieldSurface.qml` states its colours — so the shell's dark
/// scheme is restated here exactly as `ChecksPanel` restates it, and every run
/// surface reads its accent, positive and negative from this one place.
///
/// Every label function falls through to the stored spelling it was handed. A
/// state or event kind this build does not define is a *newer build's*, not a
/// bug: `EventKind` is deliberately extensible and an unknown one decodes to an
/// opaque entry rather than failing the read, so a surface that dropped it would
/// hide history that is genuinely there.
Item {
    id: vocabulary

    visible: false

    Kirigami.Theme.colorSet: Kirigami.Theme.Window
    Kirigami.Theme.inherit: false
    Kirigami.Theme.backgroundColor: "#000000"
    Kirigami.Theme.alternateBackgroundColor: "#0d0d0d"
    Kirigami.Theme.textColor: "#ffffff"

    readonly property color accentColor: Kirigami.Theme.highlightColor
    readonly property color positiveColor: Kirigami.Theme.positiveTextColor
    readonly property color negativeColor: Kirigami.Theme.negativeTextColor
    readonly property color neutralColor: Kirigami.Theme.neutralTextColor
    readonly property color dimColor: Kirigami.Theme.disabledTextColor
    readonly property color bodyColor: Kirigami.Theme.textColor
    readonly property color frameColor: Qt.alpha(Kirigami.Theme.textColor, 0.15)

    // --- Run and step lifecycle -------------------------------------------

    /// Whether a run or step state is one the runtime can still move out of.
    function pending(state) {
        return ["queued", "running", "waiting_for_approval"].indexOf(String(state)) !== -1;
    }

    function stateLabel(state) {
        const value = String(state);
        if (value === "queued")
            return qsTr("Queued");
        if (value === "running")
            return qsTr("Running");
        if (value === "waiting_for_approval")
            return qsTr("Waiting for approval");
        if (value === "succeeded")
            return qsTr("Succeeded");
        if (value === "failed")
            return qsTr("Failed");
        if (value === "cancelled")
            return qsTr("Cancelled");
        if (value === "interrupted")
            return qsTr("Interrupted");
        return value;
    }

    /// Interrupted is neutral rather than negative on purpose: nothing decided
    /// the work was wrong, the process that was driving it stopped.
    function stateColor(state) {
        const value = String(state);
        if (value === "succeeded")
            return positiveColor;
        if (value === "failed")
            return negativeColor;
        if (value === "cancelled" || value === "interrupted")
            return neutralColor;
        if (value === "waiting_for_approval")
            return neutralColor;
        if (value === "running")
            return accentColor;
        return dimColor;
    }

    // --- Tool call lifecycle ----------------------------------------------

    function callStateLabel(state) {
        const value = String(state);
        if (value === "pending")
            return qsTr("Pending");
        if (value === "awaiting_approval")
            return qsTr("Awaiting approval");
        if (value === "denied")
            return qsTr("Denied");
        return stateLabel(value);
    }

    function callStateColor(state) {
        const value = String(state);
        if (value === "denied")
            return negativeColor;
        if (value === "awaiting_approval")
            return neutralColor;
        return stateColor(value);
    }

    /// Whether a call is one the owning process stopped part-way through.
    ///
    /// `interrupted` is written by the recovery sweep and by nothing else, so a
    /// call in this state is exactly what was in flight when the process died.
    function callWasInFlight(state) {
        return String(state) === "interrupted";
    }

    // --- Approvals ---------------------------------------------------------

    function approvalStateLabel(state) {
        const value = String(state);
        if (value === "pending")
            return qsTr("Waiting for an answer");
        if (value === "granted")
            return qsTr("Approved");
        if (value === "denied")
            return qsTr("Denied");
        if (value === "expired")
            return qsTr("Expired unanswered");
        if (value === "cancelled")
            return qsTr("Cancelled with the run");
        if (value === "superseded")
            return qsTr("Superseded");
        return value;
    }

    function approvalStateColor(state) {
        const value = String(state);
        if (value === "granted")
            return positiveColor;
        if (value === "denied")
            return negativeColor;
        if (value === "pending")
            return neutralColor;
        return dimColor;
    }

    /// The risk ceiling a request was opened under, in words.
    ///
    /// The spellings are `RiskLevel::as_str`'s, in its own declaration order.
    function riskLabel(risk) {
        const value = String(risk);
        if (value === "observe")
            return qsTr("Reads only");
        if (value === "workspace_write")
            return qsTr("Writes the workspace");
        if (value === "execute")
            return qsTr("Runs a process");
        if (value === "network")
            return qsTr("Reaches the network");
        if (value === "remote_write")
            return qsTr("Writes somewhere remote");
        if (value === "destructive")
            return qsTr("Destructive");
        return value;
    }

    /// How far an approval reaches, in words.
    ///
    /// The spellings are `ApprovalScope::as_str`'s.
    function scopeLabel(scope) {
        const value = String(scope);
        if (value === "exact_call")
            return qsTr("This call only");
        if (value === "tool_for_run")
            return qsTr("This tool, for this run");
        if (value === "capability_for_run")
            return qsTr("This capability, for this run");
        return value;
    }

    // --- The event log -----------------------------------------------------

    /// The heading one timeline row shows for its event kind.
    function eventLabel(kind) {
        const value = String(kind);
        if (value === "run_state_changed")
            return qsTr("Run state");
        if (value === "run_interrupted")
            return qsTr("Run interrupted");
        if (value === "run_retried")
            return qsTr("Re-attempted");
        if (value === "step_started")
            return qsTr("Step started");
        if (value === "step_finished")
            return qsTr("Step finished");
        if (value === "tool_call_state_changed")
            return qsTr("Tool call");
        if (value === "policy_decision")
            return qsTr("Policy decision");
        if (value === "tool_progress")
            return qsTr("Progress");
        if (value === "approval_requested")
            return qsTr("Approval requested");
        if (value === "approval_decided")
            return qsTr("Approval decided");
        if (value === "approval_identity_drift")
            return qsTr("Identity changed under a grant");
        if (value === "artifact_created")
            return qsTr("Artifact stored");
        if (value === "agent_observation")
            return qsTr("Agent observed");
        if (value === "agent_action")
            return qsTr("Agent decided");
        if (value === "agent_checkpoint")
            return qsTr("Agent checkpoint");
        if (value === "snapshot_captured")
            return qsTr("Workspace snapshot");
        if (value === "context_cache_recreated")
            return qsTr("Context index rebuilt");
        if (value === "external_agent_health_checked")
            return qsTr("External agent checked");
        if (value === "external_agent_trust_invalidated")
            return qsTr("External agent trust lost");
        if (value === "diagnostic")
            return qsTr("Diagnostic");
        return value;
    }

    function eventIcon(kind) {
        const value = String(kind);
        if (value === "run_state_changed" || value === "step_started" || value === "step_finished")
            return "media-playback-start-symbolic";
        if (value === "run_interrupted" || value === "external_agent_trust_invalidated")
            return "dialog-warning-symbolic";
        if (value === "run_retried")
            return "view-refresh-symbolic";
        if (value === "tool_call_state_changed")
            return "run-build-symbolic";
        if (value === "policy_decision")
            return "security-medium-symbolic";
        if (value === "tool_progress")
            return "media-playlist-repeat-symbolic";
        if (value === "approval_requested" || value === "approval_decided"
                || value === "approval_identity_drift")
            return "dialog-question-symbolic";
        if (value === "artifact_created")
            return "document-save-symbolic";
        if (value === "snapshot_captured")
            return "camera-photo-symbolic";
        if (value === "context_cache_recreated")
            return "edit-clear-history-symbolic";
        if (value === "agent_observation" || value === "agent_action"
                || value === "agent_checkpoint" || value === "external_agent_health_checked")
            return "system-run-symbolic";
        return "dialog-information-symbolic";
    }

    /// The accent one timeline row is marked with.
    ///
    /// Read from the event's *payload summary* as well as its kind, because a
    /// state change is the same kind whether it says `succeeded` or `failed`,
    /// and the colour is the fastest thing to read when scanning a timeline.
    function eventColor(kind, summary) {
        const value = String(kind);
        const text = String(summary);
        if (value === "run_interrupted" || value === "external_agent_trust_invalidated"
                || value === "approval_identity_drift")
            return neutralColor;
        if (value === "approval_requested")
            return neutralColor;
        if (value === "run_state_changed" || value === "step_finished"
                || value === "tool_call_state_changed") {
            if (text.indexOf("state=succeeded") !== -1)
                return positiveColor;
            if (text.indexOf("state=failed") !== -1 || text.indexOf("state=denied") !== -1)
                return negativeColor;
            if (text.indexOf("state=cancelled") !== -1
                    || text.indexOf("state=interrupted") !== -1
                    || text.indexOf("state=waiting_for_approval") !== -1)
                return neutralColor;
            if (text.indexOf("state=running") !== -1)
                return accentColor;
        }
        if (value === "approval_decided")
            return text.indexOf("verdict=granted") !== -1 ? positiveColor : negativeColor;
        if (value === "policy_decision")
            return text.indexOf("verdict=deny") !== -1 ? negativeColor : dimColor;
        return dimColor;
    }

    // --- Units -------------------------------------------------------------

    function availabilityLabel(availability) {
        const value = String(availability);
        if (value === "available")
            return qsTr("Available");
        if (value === "missing")
            return qsTr("Unavailable");
        if (value === "size_mismatch")
            return qsTr("Changed since it was stored");
        return value;
    }

    function availabilityColor(availability) {
        return String(availability) === "available" ? dimColor : neutralColor;
    }

    /// Decimal units, matching what every file manager on this desktop shows.
    function bytes(count) {
        const value = Number(count || 0);
        if (value < 1000)
            return qsTr("%1 B").arg(value);
        if (value < 1000000)
            return qsTr("%1 kB").arg((value / 1000).toFixed(1));
        if (value < 1000000000)
            return qsTr("%1 MB").arg((value / 1000000).toFixed(1));
        return qsTr("%1 GB").arg((value / 1000000000).toFixed(1));
    }

    /// A stored RFC 3339 instant as a `Date`, or null when there is none.
    ///
    /// Every timestamp the runtime stores is UTC at fixed precision, which
    /// `Date` parses; an empty string means the record has not reached that
    /// point yet and is never rendered as the epoch.
    function instant(text) {
        const value = String(text || "");
        if (value.length === 0)
            return null;
        const parsed = new Date(value);
        return isNaN(parsed.getTime()) ? null : parsed;
    }

    /// A stored instant in the reader's own timezone.
    function localTime(text) {
        const parsed = instant(text);
        return parsed === null ? "" : Qt.formatDateTime(parsed, Qt.DefaultLocaleShortDate);
    }

    function clockTime(text) {
        const parsed = instant(text);
        return parsed === null ? "" : Qt.formatTime(parsed, "hh:mm:ss");
    }

    /// How long ago a stored instant was, coarsely.
    ///
    /// `now` is passed in rather than read here so a list of fifty rows shares
    /// one reading of the clock and every row agrees about what "now" is.
    function since(text, now) {
        const parsed = instant(text);
        if (parsed === null)
            return "";
        const seconds = Math.max(0, Math.round((Number(now) - parsed.getTime()) / 1000));
        if (seconds < 45)
            return qsTr("just now");
        if (seconds < 5400)
            return qsTr("%1 min ago").arg(Math.round(seconds / 60));
        if (seconds < 172800)
            return qsTr("%1 h ago").arg(Math.round(seconds / 3600));
        return qsTr("%1 d ago").arg(Math.round(seconds / 86400));
    }

    /// How long two stored instants are apart, or nothing when either is absent.
    function duration(from, to) {
        const start = instant(from);
        const end = instant(to);
        if (start === null || end === null)
            return "";
        const seconds = Math.max(0, (end.getTime() - start.getTime()) / 1000);
        if (seconds < 1)
            return qsTr("%1 ms").arg(Math.round(seconds * 1000));
        if (seconds < 60)
            return qsTr("%1 s").arg(seconds.toFixed(1));
        // Rounded to whole seconds *before* the split, so a value whose
        // remainder rounds up to sixty carries into the minute rather than
        // rendering as "1 min 60 s".
        const whole = Math.round(seconds);
        return qsTr("%1 min %2 s").arg(Math.floor(whole / 60)).arg(whole % 60);
    }

    // --- Untrusted text ----------------------------------------------------

    /// Escapes a value for a control that renders rich text whatever it is told.
    ///
    /// `Kirigami.InlineMessage` does not expose the text format of its internal
    /// label, and everything shown through one here — a failure message, a tool
    /// error, an artifact name — is tool or repository content. The same
    /// function `GitPanel` and `ChecksPanel` carry, for the same reason.
    function escapedRichText(value) {
        return "<span>" + String(value)
            .replace(/&/g, "&amp;")
            .replace(/</g, "&lt;")
            .replace(/>/g, "&gt;") + "</span>";
    }

    function escapedRichMultiline(value) {
        return escapedRichText(value).replace(/\n/g, "<br>");
    }
}
