[package]
name = "harkness-cli"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true

[[bin]]
name = "harkness"
path = "src/main.rs"

[dependencies]
base64.workspace = true
clap.workspace = true
harkness-core.workspace = true
harkness-git.workspace = true
libc.workspace = true
serde.workspace = true
serde_json.workspace = true
time.workspace = true

[dev-dependencies]
git2.workspace = true
serde_json.workspace = true
tempfile.workspace = true
